accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

generator/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', home, name='home'),
    path('generate/', generate, name="generate"),
    path('password/', password, name="password"),
    path('password_details/', password_details, name="password_details"),
]

password_generator/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator.urls')),
    path('accounts/', include('accounts.urls')),
]

generator/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class GeneratedPassword(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username} - {self.purpose}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    email = forms.EmailField(required=True)
    username = forms.CharField(help_text=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from .forms import RegisterForm
# from calculator.views import home as home_page
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)
    
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'The email or the password is not correct.')
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

generator/views.py
from django.shortcuts import render
from .models import GeneratedPassword
import random

def user_update_or_create(request, model, defaults):
    if request.user.is_authenticated:
        model.objects.create(
            user=request.user,
            **defaults
        )

def home(request):
    return render(request, 'generator/home.html')

def generate(request):
    context = {
        'weak_range': range(6, 16),
        'strong_range': range(16, 129),
        'unbelievable_range': [256, 512, 1024, 2048],
    }
    return render(request, 'generator/generate.html', context)

def password(request):
    lower_case_letters = list('abcdefghijklmnopqrstuvwxyz')
    upper_case_letters = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    numbers = list('0123456789')
    symbols = list('!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~')

    length = int(request.GET.get('length', 16))
    purpose = str(request.GET.get('purpose', ''))
    available_chars = lower_case_letters

    if request.GET.get('uppercase'):
        available_chars += upper_case_letters

    if request.GET.get('numbers'):
        available_chars += numbers

    if request.GET.get('symbols'):
        available_chars += symbols
    
    generated_password = ''.join(random.choice(available_chars) for _ in range(length))

    user_update_or_create(
        request,
        GeneratedPassword,
        {
            'password': generated_password,
            'purpose': purpose
        }
    )

    return render(request, 'generator/password.html', {'password': generated_password})

def password_details(request):
    saved_passwords = GeneratedPassword.objects.filter(user=request.user)
    return render(request, 'generator/password_details.html', {'saved_passwords': saved_passwords})

templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
      Site Title
    {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
  </head>

  <body class="background">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">PASSWORD GENERATOR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Generate Password</a>
          </li>
        </ul>
      </div>
        <ul class="navbar-nav" style="margin-right: 20px;">
            <form class="form-inline my-2 my-lg-0">
              {% if user.is_authenticated %}
                <a class="btn btn-outline-secondary" type="submit" href="{% url 'accounts:logout' %}">Log out</a>
              {% else %}
                <a class="btn btn-success" href="{% url 'accounts:login' %}">Log in</a>
                <a class="btn btn-outline-warning" href="{% url 'accounts:signup' %}">Sign up</a>
              {% endif %}
            </form>
        </ul>
    </nav>

      <div class='container'>
        <h1>{% block content%}{% endblock %}</h1>
      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

  </body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="container">
        <form class="login" method="POST" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <h4>Log in</h4>
                <hr>
                <p><div class="field-style">{{ form }}</div><br /></p>
                {% for message in messages %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endfor %}
                <input type="submit" class="submit-button" value="Log in" />
                <br />
                <p class="text-center">Not a member? <a href="{% url 'accounts:signup' %}">Signup!</a></p>
        </form>
    </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="container">
        <form class="signup" method="POST" action="{% url 'accounts:signup' %}">
                {% csrf_token %}
                <h4>Sign Up</h4>
                <p><div class="field-style">{{ form }}</div><br /></p>
                <input type="submit" class="submit-button" value="Sign Up" />
                <br />
                <p class="text-center">Do you already have an account?<br /><a href="{% url 'accounts:login' %}">Login!</a></p>
        </form>
    </div>
    <div class="space"></div>
{% endblock %}

templates/generator/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
      Site Title
    {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&family=Orbitron:wght@500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'generator/style.css' %}">
  </head>

  <body class="background">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">PASSWORD GENERATOR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'generate' %}">Generate Password</a>
          </li>
      </div>
        <ul class="navbar-nav" style="margin-right: 20px;">
            <form class="form-inline my-2 my-lg-0">
              {% if user.is_authenticated %}
              <a class="btn btn-outline-secondary" type="submit" href="{% url 'password_details' %}">Password Details</a>
                <a class="btn btn-outline-secondary" type="submit" href="{% url 'accounts:logout' %}">Log out</a>
              {% else %}
                <a class="btn btn-success" href="{% url 'accounts:login' %}">Log in</a>
                <a class="btn btn-outline-warning" href="{% url 'accounts:signup' %}">Sign up</a>
              {% endif %}
            </form>
        </ul>
    </nav>

      <div class='container'>
        <h1>{% block content%}{% endblock %}</h1>
      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

  </body>
</html>

templates/generator/generate.html
{% extends 'generator/base.html' %}

{% block content %}

<div class="container">
    <h1 style="text-align: center;">🛡️ Secure Password Generator 🔑</h1>
    <hr>
    <form action="{% url 'password' %}">
        <div>
            <label class="s-left" for="Purpose">Purpose of password:</label>
            <label class="s-right" for=""><input type="text" name="purpose" required/>( e.g. email )</label>
        </div>
        <div>
            <label for="password_length">Password Length:</label>
            <select name="length" id="password_length">
                <optgroup label="Weak">
                    {% for i in weak_range %}
                    <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </optgroup>

                <optgroup label="Strong">
                    {% for i in strong_range %}
                    {% if i == 16 %}
                    <option value="{{ i }}" selected="selected">{{ i }}</option>
                    {% else %}
                    <option value="{{ i }}">{{ i }}</option>
                    {% endif %}
                    {% endfor %}
                </optgroup>

                <optgroup label="Unbelievable">
                    {% for i in unbelievable_range %}
                    <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </optgroup>
            </select>
        </div>


        <div>
            <label class="s-left" for="lowercase">Include Lowercase Characters:</label>
            <label class="s-right" for=""><input type="checkbox" name="lowercase" id="lowercase" checked disabled />( e.g. abcdefgh )</label>
        </div>

        <div>
            <label class="s-left" for="uppercase">Include Uppercase Characters:</label>
            <label class="s-right" for=""><input type="checkbox" name="uppercase" id="uppercase">( e.g. ABCDEFGH )</label>
        </div>

        <div>
            <label class="s-left" for="numbers">Include Numbers:</label>
            <label class="s-right" for=""><input type="checkbox" name="numbers" id="numbers">( e.g. 123456 )</label>
        </div>

        <div>
            <label class="s-left" for="symbols">Include Symbols:</label>
            <label class="s-right" for=""><input type="checkbox" name="symbols" id="symbols">( e.g. @#$% )</label>
        </div>

        <div>
            <input class="mt-2 button btn btn-success" type="submit" value="Generate Password">
        </div>

    </form>
</div>

<style>
    div {
        display: block;
        font-family: 'Recursive', sans-serif;
        font-size: 17px;
    }

    .s-left {
        display: inline;
        text-align: left;
        float: left;
        width: 240px;
        margin: 0;
        padding: 0;
        height: 27px;
    }

    #password_length {
        
        width: 200px;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 20px;
        margin: 2px 0 0 4px;
    }

    .s-right {
        display: inline;
        text-align: left;
        float: left;
        width: 520px;
        margin: 0;
        padding: 0;
        height: 27px;
    }

    .button {
        box-shadow: 0 1px 3px 0px rgba(0, 0, 0, 0.4);
    }

    .container {
        width: 900px;
        margin: 15px auto;
        padding: 15px 30px 10px 30px;
        background: #ffffff;
        line-height: 23px;
        border: 1px solid #dfdfdf;
        border-radius: 10px 10px;
        overflow: hidden;
    }

    input[type="checkbox"i] {
        background-color: initial;
        cursor: default;
        -webkit-appearance: checkbox;
        box-sizing: border-box;
        margin: 3px 3px 3px 4px;
        padding: initial;
        border: initial;
    }

    input {
        -webkit-writing-mode: horizontal-tb !important;
        text-rendering: auto;
        color: -internal-light-dark-color(black, white);
        letter-spacing: normal;
        word-spacing: normal;
        text-transform: none;
        text-indent: 0px;
        text-shadow: none;
        display: inline-block;
        text-align: start;
        -webkit-appearance: textfield;
        background-color: -internal-light-dark-color(rgb(255, 255, 255), rgb(59, 59, 59));
        -webkit-rtl-ordering: logical;
        cursor: text;
        margin: 0em;
        font: 400 13.3333px Arial;
        padding: 4px 8px;
        border-width: 2px;
        border-style: inset;
        border-color: -internal-light-dark-color(rgb(118, 118, 118), rgb(195, 195, 195));
        border-image: initial;
    }
</style>

{% endblock %}

templates/generator/home.html
{% extends 'generator/base.html' %}

{% block content %}

<div class="container">
    <h1 style="text-align: center;">🛡️   Generator Secure Password🔑</h1>
    <hr>
    <div>
        <h2>Rules</h2>
        <p><strong>Weak Range:</strong> 6 to 15</p>
        <p><strong>Strong Range:</strong> 16 to 128</p>
        <p><strong>Unbelievable Range:</strong> 256, 512, 1024, 2048</p>
    </div>


    <div>
        <label class="s-left" for="lowercase">Include Lowercase Characters:</label>
    </div>

    <div>
        <label class="s-left" for="uppercase">Include Uppercase Characters:</label>
    </div>

    <div>
        <label class="s-left" for="numbers">Include Numbers:</label>
    </div>

    <div>
        <label class="s-left" for="symbols">Include Symbols:</label>
    </div>

    
</div>
<div>
    <a class="mt-2 button btn btn-success" href="{% url 'generate' %}">Go to generate password</a>
</div>

<style>
    div {
        display: block;
        font-family: 'Recursive', sans-serif;
        font-size: 17px;
    }

    .s-left {
        display: inline;
        text-align: left;
        float: left;
        width: 240px;
        margin: 0;
        padding: 0;
        height: 27px;
    }

    #password_length {
        
        width: 200px;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 20px;
        margin: 30px 0 0 30px;
    }

    .s-right {
        display: inline;
        text-align: left;
        float: left;
        width: 520px;
        margin: 0;
        padding: 0;
        height: 27px;
    }

    .button {
        box-shadow: 0 1px 3px 0px rgba(0, 0, 0, 0.4);
    }

    .container {
        width: 900px;
        margin: 15px auto;
        padding: 15px 30px 10px 30px;
        background: #ffffff;
        line-height: 23px;
        border: 1px solid #dfdfdf;
        border-radius: 10px 10px;
        overflow: hidden;
    }

</style>

{% endblock %}

templates/generator/password.html
{% extends 'generator/base.html' %}

{% block content %}

<div class="container">
    <h1 style="text-align: center;">🛡️ Secure Password Generator 🔑</h1>
    <hr>
    <div class="alert alert-success" role="alert">
        {{ password }}
    </div>

    <a href="{% url 'home' %}" type="button" class="button btn btn-secondary">Home</a>
</div>

<style>
    div {
        display: block;
        font-family: 'Recursive', sans-serif;
        font-size: 14px;
    }

    .container {
        width: 900px;
        margin: 15px auto;
        padding: 15px 30px 10px 30px;
        background: #ffffff;
        line-height: 23px;
        border: 1px solid #dfdfdf;
        border-radius: 10px 10px;
        overflow: hidden;
    }

    .button {
        box-shadow: 0 1px 3px 0px rgba(0, 0, 0, 0.4);
    }
</style>
{% endblock %}

templates/generator/password_details.html
{% extends 'generator/base.html' %}

{% block content %}
<h1>Password Details</h1>

    {% if saved_passwords %}
        <ul>
            {% for password in saved_passwords %}
                <li>
                    <strong>Purpose:</strong> {{ password.purpose }}<br>
                    <strong>Password:</strong> {{ password.password }}<br>
                    <strong>Created At:</strong> {{ password.created_at }}<br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No saved passwords.</p>
    {% endif %}
    
    <a href="{% url 'home' %}">Back to Home</a>
    {% endblock %}